### PR TITLE
qt: Fix Qt warnings

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by TingPing** [comment]
For consistency `xdg-desktop-portal` uses `G_GNUC_UNUSED`.

**Comment by grulja** [comment]
Or https://doc.qt.io/qt-5/qtglobal.html#Q_UNUSED

**Comment by hfiguiere** [comment]
`Q_UNUSED` doesn't work for function arguments as it is:
```
#define Q_UNUSED(x) (void)x;
```

**Comment by hfiguiere** [comment]
> For consistency `xdg-desktop-portal` uses `G_GNUC_UNUSED`.

Done

**Pull request merged**
