### PR TITLE
remote: Add API to allow for persistence on RemoteDesktop sessions

### LINKED ISSUE #127: No API to create persistent RemoteDesktop sessions
Required for https://github.com/input-leap/input-leap/issues/1699 - if the screensaver kicks in the RemoteDesktop Session is closed. For InputLeap we want to reconnect when it's available again, but that requires restoring the session.

`xdp_portal_create_remote_desktop_session()` doesn't allow the persist mode and restore token like `xdp_portal_create_screencast_session()` does, we'll need some new API here.

### PR DESCRIPTION
**Pull request by whot**
Same as the ScreenCast API

Fixes #127

cc @jadahl

Marking as Draft until I've sold off the right to rename this to a more sensible function name to the highest bidder. Any suggestions?

### CODE REVIEW

**Comment by GeorgesStavracas** [comment]
libportal is not API nor ABI stable, so I'd be okay with breaking API for the next stable release.

For now, I guess a `_full` variant of this function should be enough

**Comment by jadahl** [comment]
> libportal is not API nor ABI stable, so I'd be okay with breaking API for the next stable release.

Has that been the case always? If that's the case, how can libportal be suitable for any application that intends to be both distributable via Flatpak and traditional distributions?

**Comment by GeorgesStavracas** [comment]
> Has that been the case always?

That's how I've been approaching libportal development since at least 2021 :slightly_smiling_face: 

> If that's the case, how can libportal be suitable for any application that intends to be both distributable via Flatpak and traditional distributions?

Personally, I consider libportal suitable for Flatpak applications only... somewhat like a Rust / cargo dependency, you have to pinpoint the exact version you want in the manifest.

**Comment by whot** [comment]
Renamed to `_full` and tests updated and one extra new test added, should be ready.

**Review by GeorgesStavracas — APPROVED** [review]

**Comment by jadahl** [comment]
> That's how I've been approaching libportal development since at least 2021 🙂

That is not what I would have assumed. Anyway, filed https://github.com/flatpak/libportal/issues/129.

**Pull request merged**
